version: '3'

services:

  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/dockerfile
    image: blog_api_local_django
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
    ports:
      - "8000:8000"
    command: /start
  
  celery_worker:
    <<: *django
    image: blog_api_local_django_worker
    command: /worker
    ports: []

  redis:
    image: redis:5.0.4